export const SET_CURRENT_USER = 'RN_ISAC/auth/SET_CURRENT_USER';

export const LOGIN_REQUEST = 'RN_ISAC/auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'RN_ISAC/auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'RN_ISAC/auth/LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'RN_ISAC/auth/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'RN_ISAC/auth/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'RN_ISAC/auth/LOGOUT_FAILURE';

export const REGISTER_REQUEST = 'RN_ISAC/auth/REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'RN_ISAC/auth/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'RN_ISAC/auth/REGISTER_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'RN_ISAC/auth/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'RN_ISAC/auth/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'RN_ISAC/auth/FORGOT_PASSWORD_FAILURE';
